### ISSUE TITLE
Feature: Allow regex for unscramble

### ISSUE THREAD

**Issue by Thurion** [Thurion/Filename-Scramble#2]
Supply a regex as parameter and use that to determine which files should be unscrambled

**Comment by TheAntiSnipe** [comment]
Good day, @Thurion! I'd like to work on this issue, but could you clarify exactly how you want the regex parameter to function? Cheers!

**Comment by Thurion** [comment]
Added with commit 6274611592e03de5f123209c5e5e06238c3daa75
